apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${ pvc_name }
spec:
  storageClassName: efs-sc
  volumeName: ${ volume_name }
  accessModes:
    - ${ volume_access_mode }
  resource:
    requests:
      storage: ${ volume_capacity }
